FROM node:12.22.2

USER root
WORKDIR /frontend
COPY . /frontend

ARG REACT_APP_DS_RETURN_URL
ENV REACT_APP_DS_RETURN_URL=${REACT_APP_DS_RETURN_URL}

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}

RUN npm install
RUN npm build

EXPOSE 3000

CMD ["npm", "start"]